### ISSUE TITLE
Ruby errors thrown while building docs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-docs#95]
Reproduction steps:

1. Set up the docs.
1. Execute following commands:
	1. `cd ckeditor-docs`
	1. `grunt`

## Expected

Docs are built without Ruby errors.

## Actual

Ton of errors is being thrown, like:

```
/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'


/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'


/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'/var/lib/gems/2.3.0/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'
```

## Environment

* Ubuntu on Windows
* Ruby verison: `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`
* Gem version: `2.5.1`

**Comment by f1ames** [comment]
I have similar error:

```
Thread.exclusive is deprecated, use Mutex
/Users/krzysztofkrzton/.rvm/gems/ruby-2.3.3/gems/parallel-0.7.1/lib/parallel.rb:206:in `block (3 levels) in work_in_processes'
/Users/krzysztofkrzton/.rvm/gems/ruby-2.3.3/gems/parallel-0.7.1/lib/parallel.rb:204:in `loop'
/Users/krzysztofkrzton/.rvm/gems/ruby-2.3.3/gems/parallel-0.7.1/lib/parallel.rb:204:in `block (2 levels) in work_in_processes'
/Users/krzysztofkrzton/.rvm/gems/ruby-2.3.3/gems/parallel-0.7.1/lib/parallel.rb:65:in `block (2 levels) in in_threads'
```

* OS X El Capitan 10.11.6
* Ruby `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]`
* Gem: `2.6.11`
* Gems (`gem list`):

```
addressable (2.5.1)
bigdecimal (default: 1.2.8)
bundler-unload (1.0.2)
chunky_png (1.3.8)
ckeditor-jsduck (0.0.6)
colorator (1.1.0)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
did_you_mean (1.0.0)
dimensions (1.2.0)
executable-hooks (1.3.2)
ffi (1.9.18)
forwardable-extended (2.6.0)
gem-wrappers (1.2.7)
io-console (default: 0.4.5)
jekyll (3.4.3)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
jsduck (5.3.4)
json (default: 1.8.3)
kramdown (1.13.2)
liquid (3.0.6)
listen (3.0.8)
mercenary (0.3.6)
minitest (5.8.5)
multi_json (1.12.1)
net-telnet (0.1.1)
parallel (0.7.1)
pathutil (0.14.0)
power_assert (0.2.6)
psych (default: 2.1.0)
public_suffix (2.0.5)
rake (10.4.2)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdiscount (2.1.8)
rdoc (default: 4.2.1)
redcarpet (3.4.0)
rkelly-remix (0.0.7)
rouge (2.0.7, 1.11.1)
rubygems-bundler (1.4.4)
rubygems-update (2.6.11)
rvm (1.11.3.9)
safe_yaml (1.0.4)
sass (3.4.23)
test-unit (3.1.5)
```

**Comment by msamsel** [comment]
OS X Sierra 10.12.5 (16F73)
Ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
Gem: 2.0.14.1
Gems (gem list):
```
addressable (2.5.1)
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
ckeditor-jsduck (0.0.6)
colorator (1.1.0)
dimensions (1.2.0)
ffi (1.9.18)
forwardable-extended (2.6.0)
io-console (0.4.2)
jekyll (3.4.3)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (1.8.6, 1.7.7)
kramdown (1.13.2)
libxml-ruby (2.6.0)
liquid (3.0.6)
listen (3.0.8)
mercenary (0.3.6)
minitest (4.3.2)
nokogiri (1.5.6)
parallel (0.7.1)
pathutil (0.14.0)
psych (2.0.0)
public_suffix (2.0.5)
rake (0.9.6)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdiscount (2.1.8)
rdoc (4.0.0)
redcarpet (3.4.0)
rkelly-remix (0.0.7)
rouge (2.0.7, 1.11.1)
safe_yaml (1.0.4)
sass (3.4.24)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```
----
No Errors only warnings:
```
CKEditor Documentation Builder v1.0.0.
[i] CKEDITOR_DEV env variable not set. Looking for ../ckeditor-dev...
[i] Directory ../ckeditor-dev found!
[i] Using ../ckeditor-dev as source directory.

Running "jsduck:docs" (jsduck) task
Warning: /Users/msamsel/work/ckeditor-docs/guides/dev/installation/ckeditor_quick_start_download.png Image not used.
Warning: /Users/msamsel/work/ckeditor-docs/guides/dev/installation/ckeditor_sample.png Image not used.
(...)
Warning: /Users/msamsel/work/ckeditor-docs/guides/skin_sdk/compatibility_with_ckeditor_4_5/notifications.png Image not used.

Running "copy:source" (copy) task
Created 2 directories, copied 11 files

Done, without errors.
```

**Comment by mlewand** [comment]
I can confirm that with Ruby 2.0.0 it works without errors on Windows too.

```
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
$ gem --version
2.4.8
```

**Comment by msamsel** [comment]
During building appear warning related to deprecated [parallel](https://github.com/grosser/parallel) library.
It seems that proper way to fix it would be update packages use in our [fork](https://github.com/ckeditor/jsduck) of JSDuck.
Unfortunately instruction added to our fork use unavailable tools:
> 1. Install [Sencha SDK Tools](http://www.sencha.com/products/sdk-tools/download/) for your OS.

Link redirect to different place.
Further steps, which is **rake configure** throw an error:
```
Archive:  template/extjs.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of template/extjs.zip or
        template/extjs.zip.zip, and cannot find template/extjs.zip.ZIP, period.
mv: rename template/ext-4.1.1a to template/extjs: No such file or directory
sdk-vars.rb already exists. Keeping it.
```
General notes about this case:
* As far as I know file `ext-4.1.1a` is a template used by this fork to build documentation.
* According to [JSDuck docs](https://github.com/senchalabs/jsduck/wiki/Hacking), there are smoke tests. In our case those tests fails.
* Some download option for extjs library might be found [here](http://mirror.joehorn.idv.tw/extjs/).
* `Rakefile` contains function: `task :get_extjs` which tries to download zip file from link: [http://cdn.sencha.com/ext-4.1.1a-gpl.zip](http://cdn.sencha.com/ext-4.1.1a-gpl.zip). File is unavailable.
* trying to create gem without it, made package but you won't be able to build ckeditor docs. There is error:
```
CKEditor Documentation Builder v1.0.0.
[i] CKEDITOR_DEV env variable not set. Looking for ../ckeditor-dev...
[i] Directory ../ckeditor-dev found!
[i] Using ../ckeditor-dev as source directory.

Running "jsduck:docs" (jsduck) task
Error: Oh noes!  The template directory does not contain extjs/ directory :(
Error: Please copy ExtJS over to template/extjs or create symlink.
Error: For example:
Error:     $ cp -r /path/to/ext-4.0.0 /Users/msamsel/.rvm/gems/ruby-2.4.1/gems/ckeditor-jsduck-0.0.7/template-min/extjs
Warning:  Use --force to continue.

Aborted due to warnings.
```

**Comment by wwalc** [comment]
In case updating parallel dependency did not work:

https://github.com/rails/activerecord-session_store/commit/82a7540dd8095cf09fe4dd4966df2cf2001e56cb

**Comment by wwalc** [comment]
In case of future issues with parallel, this workaround did the trick as well:
https://github.com/senchalabs/jsduck/issues/653#issuecomment-253253469

**Comment by f1ames** [comment]
Closed in https://github.com/ckeditor/jsduck/issues/6.
